services:
  db:
    image: postgres:16
    container_name: app-db
    restart: always
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: thYt6WXNzuCS.E70Z-e)9F
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
